name: Tour Through
favicon: null
layout_spectrum: 0.37152486690320075
typography_spectrum: 0.9320610072463751
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5009675757028162
  lightness: 0.3257765911985189
  saturation: 0.028938077623024583
  rhythmicContrast: 0.7408696089405566
purpose: []
